import { addDaysISO, type ISODate } from '@/engine/dates';

type Event = {
  uid: string;
  title: string;
  start: ISODate;
  endExclusive: ISODate; // ICS DTEND is exclusive for all-day events
  description?: string;
};

function dt(s: ISODate): string {
  return s.replace(/-/g, '');
}

function escapeText(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/,/g, '\\,').replace(/;/g, '\\;');
}

function fold(s: string): string {
  // ICS lines should not exceed 75 octets — fold by inserting CRLF + space.
  if (s.length <= 75) return s;
  let out = '';
  for (let i = 0; i < s.length; i += 73) out += (i ? '\r\n ' : '') + s.slice(i, i + 73);
  return out;
}

function vevent(e: Event): string {
  const lines = [
    'BEGIN:VEVENT',
    `UID:${e.uid}`,
    `DTSTAMP:${dt(e.start)}T000000Z`,
    `DTSTART;VALUE=DATE:${dt(e.start)}`,
    `DTEND;VALUE=DATE:${dt(e.endExclusive)}`,
    `SUMMARY:${escapeText(e.title)}`,
  ];
  if (e.description) lines.push(`DESCRIPTION:${escapeText(e.description)}`);
  lines.push('TRANSP:TRANSPARENT');
  lines.push('END:VEVENT');
  return lines.map(fold).join('\r\n');
}

export type IcsForecast = {
  predictedStart: ISODate;
  predictedEnd: ISODate;
  confidenceLow: ISODate;
  confidenceHigh: ISODate;
  fertileStart?: ISODate;
  fertileEnd?: ISODate;
};

/**
 * Generate an ICS file with the next N predicted period windows + fertile windows.
 * Each event has a stable UID so calendar apps de-dupe on re-import.
 */
export function generateIcs(forecasts: IcsForecast[], opts?: { calendarName?: string }): string {
  const events: Event[] = [];
  forecasts.forEach((f, i) => {
    events.push({
      uid: `lumen-period-${f.predictedStart}@lumen.app`,
      title: 'Period (predicted)',
      start: f.predictedStart,
      endExclusive: addDaysISO(f.predictedEnd, 1),
      description: `Estimated window: ${f.confidenceLow} → ${f.confidenceHigh}. Generated by Lumen.`,
    });
    if (f.fertileStart && f.fertileEnd) {
      events.push({
        uid: `lumen-fertile-${f.fertileStart}@lumen.app`,
        title: 'Fertile window (estimate)',
        start: f.fertileStart,
        endExclusive: addDaysISO(f.fertileEnd, 1),
        description: 'Estimated fertile window. Not contraception. Generated by Lumen.',
      });
    }
  });

  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Lumen//EN',
    'CALSCALE:GREGORIAN',
    `X-WR-CALNAME:${escapeText(opts?.calendarName ?? 'Lumen — Cycle')}`,
    ...events.map(vevent),
    'END:VCALENDAR',
  ];
  return lines.join('\r\n');
}
